name: Run project tests

on:
  pull_request:
      branches: [main, stage, development]

permissions: 
  pull-requests: write
  contents: read

jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: cd frontend && npm ci && npm run test
